
seed: 42 #랜덤 시트(재현성)


# I/O
time_col: t_ms #csv파일에서의 시간 컬럼 이름
resample_hz: 10 #리샘플링 목표 주파수 리샘플링 생략할거면 null 또는 0으로 설정


# Columns (change to your CSV headers)
feature_cols: [uwb_x, uwb_y, yolo_x, yolo_y, speed, accel, anchor_count, fppl, cir_peak] #uwb 추정 위치(m) , yolo 추정 위치(m), 태그 속도(m/s), 태그 가속도(m/s^2) , 관측된 앵커 수, 
# For 2D error correction
target_cols: [target_dx, target_dy]
# For 1D range-error correction, comment the line above and use:
# target_cols: [range_error]


# Model (Gaussian Process)
model:
kernel: RBF # RBF | Matern
ard: true # per-feature length-scales
length_scale: 1.0
noise: 1e-3 # WhiteKernel noise
alpha: 1e-6 # numerical nugget
matern_nu: 1.5 # only if kernel=Matern
